using System.Drawing;
using System.IO;

public class ImageToRgb565Converter
{
    public ushort[] ConvertToRgb565(Bitmap bmp)
    {
        int width = bmp.Width;
        int height = bmp.Height;
        ushort[] rgb565 = new ushort[width * height];
        int idx = 0;
        for (int y = 0; y < height; y++)
        {
            for (int x = 0; x < width; x++)
            {
                Color c = bmp.GetPixel(x, y);
                ushort value = (ushort)(((c.R & 0xF8) << 8) | ((c.G & 0xFC) << 3) | (c.B >> 3));
                rgb565[idx++] = value;
            }
        }
        return rgb565;
    }

    public void WriteHeaderFile(string outputPath, string arrayName, int width, int height, ushort[] rgb565)
    {
        using var sw = new StreamWriter(outputPath);
        sw.WriteLine($"// Generated by c16bmp");
        sw.WriteLine($"#define {arrayName}_WIDTH {width}");
        sw.WriteLine($"#define {arrayName}_HEIGHT {height}");
        sw.WriteLine($"const uint16_t {arrayName}_data[{width * height}] = {{");
        for (int i = 0; i < rgb565.Length; i++)
        {
            sw.Write($"0x{rgb565[i]:X4}");
            if (i < rgb565.Length - 1) sw.Write(",");
            if ((i + 1) % 16 == 0) sw.WriteLine();
        }
        sw.WriteLine("\n};");
    }
}
